image:
  file: .gitpod.Dockerfile

checkoutLocation: repositories

tasks:
  - init: |
      mv /workspace/repositories /workspace/tmp
      mkdir /workspace/repositories
      mv /workspace/tmp /workspace/repositories/spring-petclinic-dynamic-multirepo


      if [ "$GITPOD_HEADLESS" = "true" ]; then
        export TERM=dumb
      fi
      ./add_additional_select_repositores.sh
      ./gradlew build -x test

vscode:
  extensions:
    - vscjava.vscode-java-pack
    - redhat.vscode-xml

jetbrains:
  intellij:
    prebuilds:
      version: stable
