image:
  file: .gitpod.Dockerfile

tasks:
  - init: |
      if [ "$GITPOD_HEADLESS" = "true" ]; then
        export TERM=dumb
      fi
      ./gradlew build

vscode:
  extensions:
    - vscjava.vscode-java-pack
    - redhat.vscode-xml

jetbrains:
  intellij:
    prebuilds:
      version: stable
